// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8btbnDnPpGgDMwAoJnQdOsftEejMvUE',
    appId: '1:687601632005:android:bd6c1b16a7c4b952eead6c',
    messagingSenderId: '687601632005',
    projectId: 'axperthybrid',
    storageBucket: 'axperthybrid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6TxtF1ADjdt-qEpwtCxw3OfwVVy-Csw',
    appId: '1:687601632005:ios:eff98ee97e67ec32eead6c',
    messagingSenderId: '687601632005',
    projectId: 'axperthybrid',
    storageBucket: 'axperthybrid.firebasestorage.app',
    androidClientId: '687601632005-30pe7nknmveo77luoepf53i3rnl2p4g7.apps.googleusercontent.com',
    iosClientId: '687601632005-dcsfr033dtfdaaop7ngg2f7dlb436mff.apps.googleusercontent.com',
    iosBundleId: 'com.agile.space',
  );
}
